---
title: "Assault Rate Trends Within and Around the University of Toronto: A Ten-Year Analysis"
author: "Bella MacLean"
thanks: "Code and data from this analysis are available at: https://github.com/Bellamaclean7/UofT_Neighbourhood_Assaults/tree/main"
date: "today"
date-format: "long" 
abstract: "Using data from OpenDataToronto, this paper examines the trends in assault rates from 2014 to 2023 across 13 of Toronto’s 158 neighbourhoods recognized by the City of Toronto. These 13 neighbourhoods encompass and surround the University of Toronto. This papers seeks to determine a correlation between the university's presence and assault rates in its neighbouring areas, providing insights that may inform campus safety strategies and urban planning."
format: pdf
toc: true
number-sections: true
bibliography: references.bib
---

```{r}
#| message: false
#| echo: false

#### Workspace set-up ####

## Load packages
library(tidyverse)
library(knitr)
library(ggplot2)

#read in cleaned data #
uoft_neighbourhoods <- read.csv(here::here("outputs/data/cleaned_data.csv"))
show_col_types = FALSE

#read in cleaned data #
surrounding_neighbourhoods <- read.csv(here::here("outputs/data/analysis_data.csv"))
show_col_types = FALSE
```

# Introduction

Toronto is a city known for its vibrant culture and diverse neighborhoods and is home to one of Canada's most prestigious educational institutions – the University of Toronto. The University of Toronto encompasses and shapes the nearby areas of Bay-Cloverhill, The Annex, University district, and Kensington-Chinatown. These neighbourhoods are home to both an abundance of UofT academic and student buildings and a large student population. This paper examines assault rates from 2014 to 2023 in 13 of Toronto's 158 recignized neighbourhoods, using data from OpenDataToronto [@rOpenDataToronto], to understand the safety landscape of the University of Toronto in relation to assault rates over a ten-year period.

In February of 2020, the University of Toronto released data from a two-year-old province-wide, online student survey on sexual harassment and sexual assault, saying it will paint a more detailed picture of the issues and help improve supports on campus [@citeUofTSexualViolenceData]. Originally collected as part of the 2018 Student Voices on Sexual Violence Survey, the data was then released by the Ontario government to all universities and colleges province wide. Over 117,000 students from various institutions, including over 20,000 from U of T, participated in the survey. The overview of the survey released indicated that 63 per cent of students province-wide, and 59 per cent of students at U of T, reported at least one incident of sexual harassment since the beginning of the 2017-2018 academic year [@citeUofTSexualViolenceData].

Although the Univerdity of Toronto emphasizes its ongoing commitment to student safety, the improvement of services, and raising awareness of assault and voilence, there is very little data and literature that exists on the matter. This paper aids to contribute to the investigation of violence in and around the Universities district. 

The definition of assault in Canada under Sections 265 and 266 of the Criminal Code is any physical contact without consent or any action that causes someone to believe that such contact is imminent. This can range from an actual application of force to threatening gestures that make someone fear they might be harmed. This applies to all forms of assault, including sexual assault, sexual assault with a weapon, threats to a third party or causing bodily harm and aggravated sexual assault [@citeCriminalCodeSection265].

To examine the rate of assaults within and around the University of Toronto from 2014-2023, this paper has been organized into the following sections: Data, Results, Discussion, and Conclusion.  In the Data section, I discuss the nature of the spreadsheet obtained through the City of Toronto’s OpenDataToronto Library [@rOpenDataToronto] and the steps I took to clean and analyze the data. The Results section highlights trends found during the analysis process, while the Discussion section further evaluates the trends and presents insight. Lastly, the Conclusion section summarizes the main findings from this paper.

\newpage


# References


